export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ISAUTHENTICATE = "ISAUTHENTICATE";

export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";
